name: kamaae
description: Inventory barcode scanning MVP
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_commons: ^0.8.1
  sqflite: ^2.3.0
  path: ^1.8.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  pdf: ^3.11.1
  printing: ^5.13.1
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2831.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#17140E"
  android: true
  ios: false
  web: false

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/kamaae_icon.png
  adaptive_icon_background: "#17140E"
  adaptive_icon_foreground: assets/images/kamaae_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/kamaae_splash_logo.png
    - assets/images/kamaae_icon.png
    - assets/images/kamaae_logo_paper.png
